import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Cipher Cart Backend",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return <div>{children}</div>;
};

export default RootLayout;
